### ISSUE TITLE
BO - Exception thrown by module gamification on uninstall. Property Tab->name is empty.

### ISSUE THREAD

**Issue by Matt75** [PrestaShopCorp/gamification#101]
### Describe the bug
On BO > Module Manager, error thrown on uninstall action : `Exception thrown by module gamification on uninstall. Property Tab->name is empty.`

![Exception thrown by module gamification on uninstall. Property Tab->name is empty.](https://user-images.githubusercontent.com/5262628/171034973-92891f68-0877-46ff-9d76-19debaadc109.png)

### Steps to Reproduce
Install Gamification module
Install a new Language
Set new language as employee language on profile
Uninstall Gamification module

### Technical issue

On `install` and `uninstall`, actions `enable` and `disable` are also called by PrestaShop Core, it call `Tab::enablingForModule` and `Tab::disablingForModule`, if `Tab` name is invalid in a language, `Tab::save` thrown an exception `Property Tab->name is empty`

### Additional information
php 7.4
PrestaShop 1.7.8.6
Gamification module 2.4.0

**Comment by Acidiphilium** [comment]
Anyway to fix the bug? Almost 3 years later it's still there in Prestashop 8.2 and latest gamification...

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShopCorp/gamification/pull/103

**Comment by Acidiphilium** [comment]
@matks Sure you're right and thanks for the quick answer!
